chore: replace node witj bun and prettier with biomejs
coder/codercord pull request #12
Opened 2024-06-22 23:40 UTC by matifali

2024-07-20 04:14 UTC, matifali commented
I will add a contributing guide next.

2024-07-22 14:23 UTC, phorcys420 commented on .dockerignore
I think we should add a `.dockerignore` but it's fine if we do it in another PR

2024-07-22 14:27 UTC, phorcys420 requested changes

2024-07-25 20:01 UTC, phorcys420 commented
hey @matifali -- seems like you forgot to look at the other changes I requested in the review

2024-08-07 20:47 UTC, phorcys420 commented on biome.json
> +    "indentWidth": 2,
discussed with Atif -- we'll take care about this one later

2024-08-07 20:48 UTC, phorcys420 commented on package.json
> +    "lint:ci": "bunx @biomejs/biome lint --reporter=github --verbose"
I'll look into doing this one myself :-)

2024-08-07 20:48 UTC, phorcys420 commented on .prettierignore
I'll look into doing this one myself :-)

2024-08-07 21:56 UTC, matifali commented
Is it ok to merge? @phorcys420

2024-08-07 21:57 UTC, phorcys420 commented
will add the missing things in a bit @matifali -- probably today or tomorrow

2024-08-10 16:31 UTC, phorcys420 commented on package.json
> +    "lint:ci": "bunx @biomejs/biome lint --reporter=github --verbose"
`build` isn't needed anymore as bun supports TypeScript natively but I've added a `start` script

2024-08-10 16:32 UTC, phorcys420 commented on .prettierignore
the ignored files are configured in `biome.json`, I've made it so that `biome` applies .gitignore and also added back the old prettier ignores.

2024-08-10 16:35 UTC, phorcys420 commented
@matifali i'm merging this but I think we should also look into adding commit hooks for formatting!

2024-08-10 16:35 UTC, phorcys420 approved these changes
LGTM!

2024-08-10 16:35 UTC, merged